// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID    string `json:"id"`
	First string `json:"first"`
	Last  string `json:"last"`
	Old   int    `json:"old"`
}
